---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: get full name
    full_name_with_title:
      title: Mr
      first: foo
      last: bar
    register: result

  - name: print result
    debug:
      msg: "{{ result }}"
